# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMrwm-jFpAoiRXPmfajQ6Y6C7ZpjQzZB
"""

try:
    # Код, который может вызвать ошибку (например, преобразование не-числа в int)
    number = int(input("Введите число: "))
except ValueError:
    # Код, который выполняется, если произошла ошибка ValueError
    print("Ошибка! Вы ввели неверный тип данных.")
except Exception as e:
    # Обработка всех остальных исключений
    print(f"Произошла непредвиденная ошибка: {e}")
else:
    # Код, который выполняется, если блок try завершился без ошибок
    print("Ввод успешен.")
finally:
    # Код, который выполняется всегда, независимо от ошибки
    pass

import re

# Паттерн для простейшего email: word@word.com/net/org
# (более строгие паттерны сложнее для учебной задачи)
EMAIL_PATTERN = r'[\w.-]+@[\w-]+\.(com|net|org)$'

def validate_age():
    while True:
        age_input = input("Введите ваш возраст (целое число от 0 до 120): ")
        try:
            # 1. Проверка типа данных (вызовет ValueError, если не число)
            age = int(age_input)

            # 2. Проверка диапазона (логическая проверка)
            if 0 <= age <= 120:
                print(f"✅ Возраст принят: {age}")
                return age
            else:
                print("❌ Возраст должен быть в диапазоне от 0 до 120.")
        except ValueError:
            print("❌ Ошибка ввода. Пожалуйста, введите **целое число**.")

def validate_email():
    while True:
        email = input("Введите ваш email (формат: user@domain.com): ").strip()

        # re.fullmatch проверяет, соответствует ли ВСЯ строка паттерну
        if re.fullmatch(EMAIL_PATTERN, email):
            print(f"✅ Email принят: {email}")
            return email
        else:
            print("❌ Неверный формат email. Убедитесь, что адрес содержит @ и домен .com/.net/.org")

print("--- Проверка возраста ---")
user_age = validate_age()

print("\n--- Проверка email ---")
user_email = validate_email()

print("\n--- Сводка ---")
print(f"Ввод завершен. Возраст: {user_age}, Email: {user_email}")

